### ISSUE TITLE
Does this work with the latest Terraria (as of 4/26/2015) ?

### ISSUE THREAD

**Issue by seanxpert** [wiez/TerrariaPEConnector#1]
I tried this and it doesn't seem to work.
I can confirm it's sending the pong response but the Terraria client is still not showing any server to join. Has the protocol changed that this needs to be updated? Thanks.

**Comment by wiez** [comment]
Yes the version number has changed, this should fix it ea4daaf370f96b8d43b794b756dbc13a452d604d.
Also, remember this works only on linux (and maybe mac). I didn't upload the windows version because the c code to work with winpcap is messed up, I might fix it if I have some spare time.

**Comment by seanxpert** [comment]
Thanks! That took care of the server list but that's as far as it got. When trying to connect, it took a few seconds and then I got "The connection to the host has been lost". I've tried this several times. I only have port 3801 opened. Is that enough? yes it's running on linux.

I have the (server) terraria running on 192.168.1.0 subnet and then the (client) terraria running on 192.168.0.0 subnet. The linux server is running on 192.168.0.0 subnet same as the client. They all can ping each other. Please help. Thanks!

**Comment by seanxpert** [comment]
Never mind. It works now. Thanks!
